version: '3.8'

services:
  fra1m-courses:
    build: .
    ports:
      - '3000:3000'
    container_name: fra1m-courses-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - fra1m-network

networks:
  fra1m-network:
    driver: bridge
