version: '3.8'

services:
  fra1m-courses:
    build: .
    ports:
      - '3000:3000'
    container_name: fra1m-courses-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - fra1m-network
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
      
networks:
  fra1m-network:
    driver: bridge
